name: Build release-cli multiarch container

on:
  push:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: login to docker hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin    
      - name: build the image
        run: |
          export DOCKER_CLI_EXPERIMENTAL=enabled && \
          docker buildx build --push \
          --tag ginvoicing/release-cli:latest \
          --platform linux/amd64,linux/arm64 \
          .